### ISSUE TITLE
git-lfs data quota over

### ISSUE THREAD

**Issue by yiminglin-ai** [siriusdemon/pytorch-DEX#4]
Hi, 
when pulling the repo the following error shows:
`Error downloading object: dex/pth/age_sd.pth (d754f06): Smudge error: Error downloading dex/pth/age_sd.pth (d754f06341792aecf1c5893269ae849892072532f161b63cd595d713897f5302): batch response: This repository is over its data quota. Purchase more data packs to restore access.
`
Can you maybe remove the lfs option and provide download links to the pretrained models?

**Comment by siriusdemon** [comment]
Refer to this [issue](https://github.com/siriusdemon/pytorch-DEX/issues/1)
